
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streemi
      MYSQL_USER: streemi
      MYSQL_PASSWORD: streemi
    ports:
      - "3307:3306"

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
